//This is the database of dungeon rooms for CYOA

//Rooms are stored as objects in an array
//All rooms must have an x and y position
var dungeonRooms = [
  {
    rmX: 0,
    rmY: 0,
    roomType: "health",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 0,
    rmY: 1,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 0,
    rmY: 2,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 0,
    rmY: 3,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 0,
    rmY: 4,
    roomType: "start",
    custMessage: "",
    visited: true,
  },
  {
    rmX: 1,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 2,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 2,
    rmY: 1,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 2,
    rmY: 2,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 3,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 4,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 4,
    rmY: 1,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 4,
    rmY: 2,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 4,
    rmY: 3,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 4,
    rmY: 4,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 5,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 6,
    rmY: 0,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 7,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 7,
    rmY: 1,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 7,
    rmY: 2,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 7,
    rmY: 3,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 7,
    rmY: 4,
    roomType: "boss1",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 8,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 9,
    rmY: 0,
    roomType: "health",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 10,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 10,
    rmY: 1,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 10,
    rmY: 2,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 10,
    rmY: 3,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 10,
    rmY: 4,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 11,
    rmY: 0,
    roomType: "empty",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 11,
    rmY: 2,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 11,
    rmY: 4,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 12,
    rmY: 0,
    roomType: "monster",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 12,
    rmY: 2,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 12,
    rmY: 4,
    roomType: "health",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 13,
    rmY: 0,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 13,
    rmY: 1,
    roomType: "trader",
    custMessage: "",
    visited: false,
  },
  {
    rmX: 13,
    rmY: 3,
    roomType: "chest",
    opened: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 13,
    rmY: 4,
    roomType: "boss2",
    beaten: false,
    custMessage: "",
    visited: false,
  },
  {
    rmX: 14,
    rmY: 4,
    roomType: "final-boss",
    beaten: false,
    custMessage: "",
    visited: false,
  },
];